version: '3.7'

services:
  nest-app-prod:
    hostname: nest-app-prod
    image: nest-app-prod
    restart: always
    build:
      context: .
      target: prod
    ports:
      - 3000:${EXPOSE_PORT:-80}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
